#!/bin/bash

echo "🧪 Testing Stripe Webhook by Creating Real Test Events"
echo ""
echo "Option 1: Check recent webhook events"
echo "========================================="
echo "Go to: https://dashboard.stripe.com/workbench/webhooks/playful-oasis"
echo "Look at the 'Events' tab to see recent deliveries"
echo ""
echo "Option 2: Trigger via Stripe Dashboard"
echo "========================================="
echo "1. Go to: https://dashboard.stripe.com/test/subscriptions"
echo "2. Create a test subscription"
echo "3. This will trigger customer.subscription.created event"
echo "4. Check webhook received it in Events tab"
echo ""
echo "Option 3: Use Stripe CLI (after re-authentication)"
echo "========================================="
echo "Run these commands:"
echo ""
echo "  stripe login"
echo "  stripe trigger customer.subscription.created"
echo ""
echo "Option 4: Check webhook health directly"
echo "========================================="
curl -I https://autopilotamerica.com/api/webhooks/stripe
echo ""
echo "✅ If you see '405 Method Not Allowed' or '400 Bad Request', the endpoint exists!"
echo "❌ If you see '404 Not Found', there's still a problem"
echo ""
