/**
 * Lob.com Mail Service Integration
 * Handles automated letter mailing for contest submissions
 */

interface MailingAddress {
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
}

// Chicago Department of Finance - Parking Ticket Contest Address
// Per city website: must be signed by registered owner
export const CHICAGO_PARKING_CONTEST_ADDRESS: MailingAddress = {
  name: 'City of Chicago - Department of Finance',
  address: 'PO Box 88292',
  city: 'Chicago',
  state: 'IL',
  zip: '60680-1292'
};

// Cook County Board of Review - Property Tax Appeals Address
// For filing residential property tax appeals
export const COOK_COUNTY_BOR_ADDRESS: MailingAddress = {
  name: 'Cook County Board of Review',
  address: '118 N. Clark Street, Room 601',
  city: 'Chicago',
  state: 'IL',
  zip: '60602'
};

interface SendLetterParams {
  from: MailingAddress; // User's address (sender)
  to: MailingAddress; // City department address (recipient)
  letterContent: string; // HTML content of the letter
  description?: string;
  metadata?: Record<string, string>;
}

interface LobMailResponse {
  id: string;
  url: string;
  tracking_number?: string;
  expected_delivery_date?: string;
}

/**
 * Send a letter via Lob.com
 * from = User's address (appears as sender)
 * to = City department (recipient)
 */
export async function sendLetter(params: SendLetterParams): Promise<LobMailResponse> {
  const { from, to, letterContent, description, metadata } = params;

  if (!process.env.LOB_API_KEY) {
    throw new Error('LOB_API_KEY not configured');
  }

  const lobApiKey = process.env.LOB_API_KEY;
  const authHeader = 'Basic ' + Buffer.from(lobApiKey + ':').toString('base64');

  try {
    console.log('Sending letter via Lob API...');
    console.log('  From:', from.name, '-', from.address, from.city, from.state, from.zip);
    console.log('  To:', to.name, '-', to.address, to.city, to.state, to.zip);
    console.log('  Letter content length:', letterContent.length, 'chars');

    // Lob API expects letter content as HTML
    const response = await fetch('https://api.lob.com/v1/letters', {
      method: 'POST',
      headers: {
        'Authorization': authHeader,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        description: description || 'Contest letter mailing',
        to: {
          name: to.name,
          address_line1: to.address,
          address_city: to.city,
          address_state: to.state,
          address_zip: to.zip,
          address_country: 'US'
        },
        from: {
          name: from.name,
          address_line1: from.address,
          address_city: from.city,
          address_state: from.state,
          address_zip: from.zip,
          address_country: 'US'
        },
        file: letterContent, // HTML string
        color: false, // Black & white printing (cheaper)
        double_sided: false,
        use_type: 'operational', // Required by Lob - operational for transactional mail like contest letters
        metadata: metadata || {}
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Lob API error response:', JSON.stringify(errorData, null, 2));
      console.error('Lob API status code:', response.status);
      const errorMessage = errorData.error?.message || errorData.message || JSON.stringify(errorData);
      throw new Error(`Lob API error (${response.status}): ${errorMessage}`);
    }

    const data = await response.json();

    return {
      id: data.id,
      url: data.url,
      tracking_number: data.tracking_number,
      expected_delivery_date: data.expected_delivery_date
    };

  } catch (error) {
    console.error('Error sending letter via Lob:', error);
    throw error;
  }
}

/**
 * Red-light camera evidence data for the Lob exhibit page.
 * This is a simplified view of the data — the full PDF report
 * is generated by lib/red-light-evidence-report.ts.
 */
export interface RedLightEvidenceExhibit {
  cameraAddress: string;
  deviceTimestamp: string;           // ISO string
  approachSpeedMph: number | null;
  minSpeedMph: number | null;
  speedDeltaMph: number | null;
  fullStopDetected: boolean;
  fullStopDurationSec: number | null;
  gpsAccuracyMeters: number | null;
  tracePointCount: number;
  traceDurationSec: number;
  /** Key speed readings from the trace (sampled) */
  speedProfile: { elapsedSec: number; speedMph: number }[];
  /** Accelerometer summary */
  accelSamples?: number;
  peakDecelG?: number;
  /** Violation timestamp from portal (if available) */
  violationDatetime?: string | null;
  timeDiffMinutes?: number | null;
  /** SHA-256 hash */
  evidenceHash: string;
  receiptId: string;

  // ── New defense analysis fields (Mar 2026) ──

  /** Yellow light timing analysis */
  yellowLight?: {
    postedSpeedMph: number;
    iteRecommendedSec: number;
    chicagoActualSec: number;
    shortfallSec: number;
    isShorterThanStandard: boolean;
    explanation: string;
    standardCitation: string;
  } | null;

  /** Right-turn-on-red detection */
  rightTurn?: {
    rightTurnDetected: boolean;
    headingChangeDeg: number;
    stoppedBeforeTurn: boolean;
    minSpeedBeforeTurnMph: number;
    isLegalRightOnRed: boolean;
    explanation: string;
  } | null;

  /** Intersection geometry */
  geometry?: {
    approachDistanceMeters: number;
    closestPointToCamera: number;
    averageApproachSpeedMph: number;
    summary: string;
  } | null;

  /** Weather/visibility at violation time */
  weather?: {
    hasAdverseConditions: boolean;
    temperatureF: number | null;
    visibilityMiles: number | null;
    impairedVisibility: boolean;
    precipitationType: string | null;
    roadCondition: string | null;
    sunPosition: string | null;
    description: string;
    defenseArguments: string[];
    source: string;
  } | null;

  /** Overall defense score (0-100) */
  defenseScore?: number;

  /** Ordered defense arguments */
  defenseArguments?: {
    type: string;
    strength: string;
    title: string;
    summary: string;
  }[];
}

/**
 * Maximum number of user evidence images to include.
 * Street View images are separate and don't count toward this limit.
 */
const MAX_USER_EVIDENCE_IMAGES = 5;

/**
 * Direction labels for Street View images
 */
const DIRECTION_LABELS: Record<number, string> = {
  0: 'North',
  1: 'East',
  2: 'South',
  3: 'West',
};

/**
 * Convert plain text letter to HTML format for Lob.
 * Optionally includes signature image, user evidence images, Street View images,
 * and red-light camera evidence exhibit.
 *
 * @param letterText - The letter content text
 * @param options.signatureImage - Optional signature image URL
 * @param options.evidenceImages - Array of user evidence image URLs (max 5 will be included)
 * @param options.streetViewImages - Array of Street View image URLs (N/E/S/W directions)
 * @param options.streetViewDate - Date of the Street View imagery (e.g., "2024-07")
 * @param options.streetViewAddress - Address shown in the Street View images
 * @param options.redLightEvidence - Red-light camera sensor data exhibit
 */
export function formatLetterAsHTML(
  letterText: string,
  options?: {
    signatureImage?: string;
    evidenceImages?: string[];
    streetViewImages?: string[];
    streetViewDate?: string | null;
    streetViewAddress?: string | null;
    redLightEvidence?: RedLightEvidenceExhibit;
  }
): string {
  const { signatureImage, evidenceImages, streetViewImages, streetViewDate, streetViewAddress, redLightEvidence } = options || {};

  // Clean up the letter text - remove leading/trailing delimiters and whitespace
  let cleanedText = letterText.trim();
  // Remove markdown-style delimiters that AI might add
  if (cleanedText.startsWith('---')) {
    cleanedText = cleanedText.replace(/^---\s*\n?/, '');
  }
  if (cleanedText.endsWith('---')) {
    cleanedText = cleanedText.replace(/\n?---\s*$/, '');
  }

  // Escape HTML entities
  const escaped = cleanedText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Convert line breaks to <br> and wrap in basic HTML structure
  const withBreaks = escaped.replace(/\n/g, '<br>');

  // Add signature if provided
  const signatureHTML = signatureImage
    ? `<div style="margin-top: 30px;">
        <p style="margin-bottom: 10px;">Signature:</p>
        <img src="${signatureImage}" alt="Signature" style="max-width: 300px; height: auto; border-bottom: 1px solid #000;" />
      </div>`
    : '';

  // Track exhibit numbering across all evidence types
  let exhibitNumber = 1;

  // Add Street View images (these go first as signage evidence)
  let streetViewHTML = '';
  if (streetViewImages && streetViewImages.length > 0) {
    const locationLabel = streetViewAddress || 'Ticket Location';
    const dateLabel = streetViewDate ? ` (Imagery Date: ${streetViewDate})` : '';

    streetViewHTML = `
      <div style="page-break-before: always; margin-top: 30px;">
        <h3 style="font-size: 14pt; margin-bottom: 10px; border-bottom: 2px solid #000; padding-bottom: 8px;">
          Exhibit A: Google Street View Signage Evidence
        </h3>
        <p style="font-size: 10pt; color: #333; margin-bottom: 15px;">
          Location: ${locationLabel}${dateLabel}<br>
          The following ${streetViewImages.length} photographs show the signage conditions at the citation location
          from each cardinal direction, as captured by Google Street View.
          These images are publicly available and can be independently verified.
        </p>
        ${streetViewImages.map((url, index) => `
          <div style="margin-bottom: 15px; ${index === 2 ? 'page-break-before: always;' : ''}">
            <p style="font-size: 10pt; font-weight: bold; margin-bottom: 5px;">
              Exhibit ${exhibitNumber++}: ${DIRECTION_LABELS[index] || `Direction ${index + 1}`}-Facing View
            </p>
            <img src="${url}" alt="Street View - ${DIRECTION_LABELS[index] || `Direction ${index + 1}`}" style="max-width: 100%; max-height: 350px; border: 1px solid #999;" />
          </div>
        `).join('')}
      </div>
    `;
  }

  // Add user evidence images if provided (limit to MAX_USER_EVIDENCE_IMAGES)
  let evidenceHTML = '';
  if (evidenceImages && evidenceImages.length > 0) {
    const imagesToInclude = evidenceImages.slice(0, MAX_USER_EVIDENCE_IMAGES);

    evidenceHTML = `
      <div style="page-break-before: always; margin-top: 30px;">
        <h3 style="font-size: 14pt; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 8px;">
          ${streetViewImages && streetViewImages.length > 0 ? 'Exhibit B: ' : ''}Additional Supporting Evidence
        </h3>
        ${imagesToInclude.map((url, index) => `
          <div style="margin-bottom: 20px; ${index > 0 && index % 2 === 0 ? 'page-break-before: always;' : ''}">
            <p style="font-size: 10pt; font-weight: bold; margin-bottom: 5px;">Exhibit ${exhibitNumber++}</p>
            <img src="${url}" alt="Evidence ${index + 1}" style="max-width: 100%; max-height: 400px; border: 1px solid #ccc;" />
          </div>
        `).join('')}
      </div>
    `;
  }

  // Add red-light camera evidence exhibit (sensor data table + speed profile)
  let redLightEvidenceHTML = '';
  if (redLightEvidence) {
    const exhibitLabel = streetViewImages?.length
      ? (evidenceImages?.length ? 'Exhibit C' : 'Exhibit B')
      : (evidenceImages?.length ? 'Exhibit B' : 'Exhibit A');

    const formatTs = (iso: string) => {
      try {
        const d = new Date(iso);
        return d.toLocaleString('en-US', {
          timeZone: 'America/Chicago',
          year: 'numeric', month: 'long', day: 'numeric',
          hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true,
        });
      } catch { return iso; }
    };

    const fullStopStyle = redLightEvidence.fullStopDetected
      ? 'background: #e8f5e9; border: 2px solid #4caf50; padding: 10px; margin: 10px 0; font-weight: bold; color: #1b5e20;'
      : '';

    // Build speed profile table rows (show up to 25 sampled readings)
    const speedRows = redLightEvidence.speedProfile.slice(0, 25).map(p => {
      const barWidth = Math.min(200, Math.max(2, (p.speedMph / 35) * 200));
      const barColor = p.speedMph <= 2.0 ? '#4caf50' : p.speedMph <= 10 ? '#ff9800' : '#f44336';
      const rowBg = p.speedMph <= 2.0 ? 'background: #e8f5e9;' : '';
      return `<tr style="${rowBg}">
        <td style="padding: 2px 8px; border: 1px solid #ddd; text-align: right;">${p.elapsedSec.toFixed(1)}s</td>
        <td style="padding: 2px 8px; border: 1px solid #ddd; text-align: right; ${p.speedMph <= 2.0 ? 'font-weight: bold; color: #1b5e20;' : ''}">${p.speedMph.toFixed(1)}</td>
        <td style="padding: 2px 4px; border: 1px solid #ddd;">
          <div style="width: ${barWidth}px; height: 10px; background: ${barColor};"></div>
        </td>
      </tr>`;
    }).join('');

    // Timestamp correlation section
    let timestampSection = '';
    if (redLightEvidence.violationDatetime) {
      const diffMin = redLightEvidence.timeDiffMinutes ?? 0;
      const matchQuality = diffMin < 5
        ? '<span style="color: #1b5e20; font-weight: bold;">STRONG MATCH</span> — device capture closely matches violation time'
        : diffMin < 60
        ? '<span style="color: #e65100;">POSSIBLE MATCH</span> — within one hour of violation time'
        : '<span style="color: #666;">WEAK MATCH</span>';

      timestampSection = `
        <tr><td colspan="2" style="padding: 8px 0 4px; font-weight: bold; font-size: 11pt; border-top: 2px solid #000;">Timestamp Correlation</td></tr>
        <tr><td style="padding: 3px 0; color: #555; width: 200px;">City Violation Time:</td><td style="padding: 3px 0;">${formatTs(redLightEvidence.violationDatetime)}</td></tr>
        <tr><td style="padding: 3px 0; color: #555;">Device Capture Time:</td><td style="padding: 3px 0;">${formatTs(redLightEvidence.deviceTimestamp)}</td></tr>
        <tr><td style="padding: 3px 0; color: #555;">Time Difference:</td><td style="padding: 3px 0;">${diffMin < 1 ? 'Less than 1 minute' : `${diffMin.toFixed(1)} minutes`}</td></tr>
        <tr><td style="padding: 3px 0; color: #555;">Correlation:</td><td style="padding: 3px 0;">${matchQuality}</td></tr>
      `;
    }

    // Accel section
    let accelSection = '';
    if (redLightEvidence.accelSamples && redLightEvidence.accelSamples > 10) {
      accelSection = `
        <tr><td colspan="2" style="padding: 8px 0 4px; font-weight: bold; font-size: 11pt; border-top: 2px solid #000;">Accelerometer Analysis</td></tr>
        <tr><td style="padding: 3px 0; color: #555;">Samples Recorded:</td><td style="padding: 3px 0;">${redLightEvidence.accelSamples}</td></tr>
        ${redLightEvidence.peakDecelG ? `<tr><td style="padding: 3px 0; color: #555;">Peak Acceleration:</td><td style="padding: 3px 0;">${redLightEvidence.peakDecelG.toFixed(3)} G</td></tr>` : ''}
      `;
    }

    redLightEvidenceHTML = `
      <div style="page-break-before: always; margin-top: 30px;">
        <h3 style="font-size: 14pt; margin-bottom: 10px; border-bottom: 2px solid #000; padding-bottom: 8px;">
          ${exhibitLabel}: Red Light Camera — Vehicle Sensor Data
        </h3>
        <p style="font-size: 9pt; color: #555; margin-bottom: 15px;">
          The following data was captured by the Autopilot mobile application at the time the vehicle passed through this intersection.
          GPS position, speed, and accelerometer readings are recorded automatically by the device's sensors.
        </p>

        ${redLightEvidence.fullStopDetected ? `
          <div style="${fullStopStyle}">
            FINDING: Vehicle came to a COMPLETE STOP at this intersection.
            ${redLightEvidence.fullStopDurationSec != null ? `Stop duration: ${redLightEvidence.fullStopDurationSec.toFixed(1)} seconds.` : ''}
          </div>
        ` : ''}

        <table style="border-collapse: collapse; width: 100%; font-size: 10pt; margin-bottom: 15px;">
          <tr><td colspan="2" style="padding: 8px 0 4px; font-weight: bold; font-size: 11pt;">Evidence Summary</td></tr>
          <tr><td style="padding: 3px 0; color: #555; width: 200px;">Camera Location:</td><td style="padding: 3px 0;">${redLightEvidence.cameraAddress}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">Date &amp; Time:</td><td style="padding: 3px 0;">${formatTs(redLightEvidence.deviceTimestamp)}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">GPS Accuracy:</td><td style="padding: 3px 0;">${redLightEvidence.gpsAccuracyMeters != null ? `${redLightEvidence.gpsAccuracyMeters.toFixed(1)} meters` : 'N/A'}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">Approach Speed:</td><td style="padding: 3px 0;">${redLightEvidence.approachSpeedMph != null ? `${redLightEvidence.approachSpeedMph.toFixed(1)} mph` : 'N/A'}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">Minimum Speed:</td><td style="padding: 3px 0;">${redLightEvidence.minSpeedMph != null ? `${redLightEvidence.minSpeedMph.toFixed(1)} mph` : 'N/A'}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">Speed Reduction:</td><td style="padding: 3px 0;">${redLightEvidence.speedDeltaMph != null ? `${redLightEvidence.speedDeltaMph.toFixed(1)} mph` : 'N/A'}</td></tr>
          <tr><td style="padding: 3px 0; color: #555;">Full Stop Detected:</td><td style="padding: 3px 0; ${redLightEvidence.fullStopDetected ? 'font-weight: bold; color: #1b5e20;' : ''}">${redLightEvidence.fullStopDetected ? 'YES' : 'No'}</td></tr>
          ${redLightEvidence.fullStopDetected && redLightEvidence.fullStopDurationSec != null ? `<tr><td style="padding: 3px 0; color: #555;">Stop Duration:</td><td style="padding: 3px 0; font-weight: bold; color: #1b5e20;">${redLightEvidence.fullStopDurationSec.toFixed(1)} seconds</td></tr>` : ''}
          <tr><td style="padding: 3px 0; color: #555;">GPS Trace Points:</td><td style="padding: 3px 0;">${redLightEvidence.tracePointCount} readings over ${redLightEvidence.traceDurationSec.toFixed(0)}s</td></tr>
          ${timestampSection}
          ${accelSection}
        </table>

        ${speedRows ? `
          <h4 style="font-size: 11pt; margin: 15px 0 5px;">Speed Profile Over Time</h4>
          <p style="font-size: 8pt; color: #666; margin-bottom: 5px;">Each row represents one GPS speed reading. Green rows indicate vehicle was stopped or near-stopped (&le; 2 mph).</p>
          <table style="border-collapse: collapse; font-size: 9pt; width: auto;">
            <tr style="background: #f5f5f5;">
              <th style="padding: 3px 8px; border: 1px solid #ddd; text-align: right;">Time</th>
              <th style="padding: 3px 8px; border: 1px solid #ddd; text-align: right;">MPH</th>
              <th style="padding: 3px 8px; border: 1px solid #ddd; text-align: left;">Speed</th>
            </tr>
            ${speedRows}
          </table>
        ` : ''}

        ${redLightEvidence.yellowLight?.isShorterThanStandard ? `
          <div style="margin-top: 15px; padding: 12px; background: #fff3e0; border: 2px solid #ff9800; font-size: 10pt;">
            <strong style="color: #e65100;">Yellow Light Timing Analysis</strong><br>
            <table style="border-collapse: collapse; font-size: 9pt; margin-top: 6px; width: 100%;">
              <tr><td style="padding: 2px 0; color: #bf360c; width: 180px;">Posted Speed:</td><td style="padding: 2px 0;">${redLightEvidence.yellowLight.postedSpeedMph} mph</td></tr>
              <tr><td style="padding: 2px 0; color: #bf360c;">Chicago Yellow Duration:</td><td style="padding: 2px 0; font-weight: bold;">${redLightEvidence.yellowLight.chicagoActualSec.toFixed(1)} seconds</td></tr>
              <tr><td style="padding: 2px 0; color: #bf360c;">ITE/MUTCD Recommended:</td><td style="padding: 2px 0; font-weight: bold;">${redLightEvidence.yellowLight.iteRecommendedSec.toFixed(1)} seconds</td></tr>
              <tr><td style="padding: 2px 0; color: #bf360c;">Shortfall:</td><td style="padding: 2px 0; font-weight: bold; color: #d32f2f;">${redLightEvidence.yellowLight.shortfallSec.toFixed(1)} seconds below standard</td></tr>
            </table>
            <p style="font-size: 8pt; color: #795548; margin: 6px 0 0;">
              Standard: ${redLightEvidence.yellowLight.standardCitation}
            </p>
          </div>
        ` : ''}

        ${redLightEvidence.rightTurn?.rightTurnDetected ? `
          <div style="margin-top: 15px; padding: 12px; background: ${redLightEvidence.rightTurn.isLegalRightOnRed ? '#e8f5e9' : '#fff8e1'}; border: 2px solid ${redLightEvidence.rightTurn.isLegalRightOnRed ? '#4caf50' : '#ffc107'}; font-size: 10pt;">
            <strong style="color: ${redLightEvidence.rightTurn.isLegalRightOnRed ? '#1b5e20' : '#f57f17'};">
              ${redLightEvidence.rightTurn.isLegalRightOnRed ? 'FINDING: Legal Right-Turn-on-Red Detected' : 'Right Turn Detected'}
            </strong><br>
            <table style="border-collapse: collapse; font-size: 9pt; margin-top: 6px; width: 100%;">
              <tr><td style="padding: 2px 0; color: #555; width: 180px;">Heading Change:</td><td style="padding: 2px 0;">${redLightEvidence.rightTurn.headingChangeDeg.toFixed(0)}&deg; clockwise (right turn)</td></tr>
              <tr><td style="padding: 2px 0; color: #555;">Stopped Before Turn:</td><td style="padding: 2px 0; font-weight: bold; color: ${redLightEvidence.rightTurn.stoppedBeforeTurn ? '#1b5e20' : '#e65100'};">${redLightEvidence.rightTurn.stoppedBeforeTurn ? 'YES' : 'No'} (min speed: ${redLightEvidence.rightTurn.minSpeedBeforeTurnMph.toFixed(1)} mph)</td></tr>
            </table>
            <p style="font-size: 8pt; color: #555; margin: 6px 0 0;">
              Under 625 ILCS 5/11-306(c), right turns on red are permitted after a complete stop unless posted otherwise.
            </p>
          </div>
        ` : ''}

        ${redLightEvidence.weather?.hasAdverseConditions ? `
          <div style="margin-top: 15px; padding: 12px; background: #e3f2fd; border: 1px solid #2196f3; font-size: 10pt;">
            <strong style="color: #0d47a1;">Weather Conditions at Time of Violation</strong><br>
            <table style="border-collapse: collapse; font-size: 9pt; margin-top: 6px; width: 100%;">
              <tr><td style="padding: 2px 0; color: #1565c0; width: 180px;">Conditions:</td><td style="padding: 2px 0;">${redLightEvidence.weather.description}</td></tr>
              ${redLightEvidence.weather.temperatureF != null ? `<tr><td style="padding: 2px 0; color: #1565c0;">Temperature:</td><td style="padding: 2px 0;">${Math.round(redLightEvidence.weather.temperatureF)}&deg;F</td></tr>` : ''}
              ${redLightEvidence.weather.visibilityMiles != null ? `<tr><td style="padding: 2px 0; color: #1565c0;">Visibility:</td><td style="padding: 2px 0; ${redLightEvidence.weather.impairedVisibility ? 'font-weight: bold; color: #d32f2f;' : ''}">${redLightEvidence.weather.visibilityMiles.toFixed(1)} miles${redLightEvidence.weather.impairedVisibility ? ' (IMPAIRED)' : ''}</td></tr>` : ''}
              ${redLightEvidence.weather.roadCondition ? `<tr><td style="padding: 2px 0; color: #1565c0;">Road Conditions:</td><td style="padding: 2px 0; font-weight: bold;">${redLightEvidence.weather.roadCondition}</td></tr>` : ''}
              ${redLightEvidence.weather.sunPosition ? `<tr><td style="padding: 2px 0; color: #1565c0;">Time of Day:</td><td style="padding: 2px 0;">${redLightEvidence.weather.sunPosition.charAt(0).toUpperCase() + redLightEvidence.weather.sunPosition.slice(1)}</td></tr>` : ''}
            </table>
            <p style="font-size: 8pt; color: #1565c0; margin: 6px 0 0;">
              Source: ${redLightEvidence.weather.source}
            </p>
          </div>
        ` : ''}

        ${redLightEvidence.geometry ? `
          <div style="margin-top: 15px;">
            <table style="border-collapse: collapse; font-size: 9pt; width: 100%;">
              <tr><td colspan="2" style="padding: 6px 0 3px; font-weight: bold; font-size: 10pt; border-top: 1px solid #ddd;">Intersection Approach Analysis</td></tr>
              <tr><td style="padding: 2px 0; color: #555; width: 200px;">Approach Distance:</td><td style="padding: 2px 0;">${redLightEvidence.geometry.approachDistanceMeters.toFixed(0)} meters</td></tr>
              <tr><td style="padding: 2px 0; color: #555;">Closest Point to Camera:</td><td style="padding: 2px 0;">${redLightEvidence.geometry.closestPointToCamera.toFixed(0)} meters</td></tr>
              <tr><td style="padding: 2px 0; color: #555;">Avg Approach Speed:</td><td style="padding: 2px 0;">${redLightEvidence.geometry.averageApproachSpeedMph.toFixed(1)} mph</td></tr>
            </table>
          </div>
        ` : ''}

        ${redLightEvidence.defenseScore != null ? `
          <div style="margin-top: 15px; padding: 10px; background: #f3e5f5; border: 1px solid #9c27b0; font-size: 9pt;">
            <strong style="color: #4a148c;">Defense Analysis Summary</strong>
            <span style="float: right; font-weight: bold; color: ${redLightEvidence.defenseScore >= 50 ? '#1b5e20' : redLightEvidence.defenseScore >= 25 ? '#e65100' : '#666'};">
              Score: ${redLightEvidence.defenseScore}/100
            </span>
            ${redLightEvidence.defenseArguments && redLightEvidence.defenseArguments.length > 0 ? `
              <ul style="margin: 6px 0 0; padding-left: 16px; font-size: 8pt;">
                ${redLightEvidence.defenseArguments.map(a =>
                  `<li style="margin-bottom: 3px;"><strong>[${a.strength.toUpperCase()}]</strong> ${a.title}: ${a.summary}</li>`
                ).join('')}
              </ul>
            ` : ''}
          </div>
        ` : ''}

        <div style="margin-top: 20px; padding: 10px; background: #f9f9f9; border: 1px solid #ddd; font-size: 8pt;">
          <strong>Data Integrity:</strong> SHA-256 hash: <code style="font-size: 7pt; word-break: break-all;">${redLightEvidence.evidenceHash}</code><br>
          Evidence ID: ${redLightEvidence.receiptId} — Data stored at autopilotamerica.com and independently verifiable.
        </div>

        <p style="font-size: 7pt; color: #999; margin-top: 10px;">
          This exhibit was generated from GPS and accelerometer data captured by the Autopilot mobile application.
          All sensor readings are recorded automatically by the device at the time of the event.
        </p>
      </div>
    `;
  }

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.3;
      margin: 0.75in 0.75in 0.5in 0.75in;
    }
    @media print {
      img { max-width: 100%; height: auto; }
    }
    @page {
      margin: 0.5in;
    }
  </style>
</head>
<body>
  ${withBreaks}
  ${signatureHTML}
  ${streetViewHTML}
  ${evidenceHTML}
  ${redLightEvidenceHTML}
</body>
</html>
  `.trim();
}

/**
 * Send a property tax appeal letter with PDF attachment via Lob
 * Uses Lob's letter API with PDF file support
 */
interface SendPropertyTaxAppealParams {
  from: MailingAddress;
  pdfUrl: string; // URL to the generated appeal PDF
  appealId: string;
  pin: string;
  township: string;
  useCertifiedMail?: boolean;
}

export async function sendPropertyTaxAppealLetter(
  params: SendPropertyTaxAppealParams
): Promise<LobMailResponse> {
  const { from, pdfUrl, appealId, pin, township, useCertifiedMail = false } = params;

  if (!process.env.LOB_API_KEY) {
    throw new Error('LOB_API_KEY not configured');
  }

  const lobApiKey = process.env.LOB_API_KEY;
  const authHeader = 'Basic ' + Buffer.from(lobApiKey + ':').toString('base64');

  try {
    const response = await fetch('https://api.lob.com/v1/letters', {
      method: 'POST',
      headers: {
        'Authorization': authHeader,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        description: `Property Tax Appeal - ${pin} - ${township}`,
        to: {
          name: COOK_COUNTY_BOR_ADDRESS.name,
          address_line1: COOK_COUNTY_BOR_ADDRESS.address,
          address_city: COOK_COUNTY_BOR_ADDRESS.city,
          address_state: COOK_COUNTY_BOR_ADDRESS.state,
          address_zip: COOK_COUNTY_BOR_ADDRESS.zip,
          address_country: 'US'
        },
        from: {
          name: from.name,
          address_line1: from.address,
          address_city: from.city,
          address_state: from.state,
          address_zip: from.zip,
          address_country: 'US'
        },
        file: pdfUrl, // Lob accepts PDF URL
        color: false,
        double_sided: true, // Property tax appeals can be multi-page
        address_placement: 'top_first_page',
        extra_service: useCertifiedMail ? 'certified' : undefined,
        use_type: 'operational', // Required by Lob - operational for transactional mail
        metadata: {
          appealId,
          pin,
          township,
          type: 'property_tax_appeal'
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Lob API error for property tax appeal:', errorData);
      throw new Error(`Lob API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();

    return {
      id: data.id,
      url: data.url,
      tracking_number: data.tracking_number,
      expected_delivery_date: data.expected_delivery_date
    };

  } catch (error) {
    console.error('Error sending property tax appeal via Lob:', error);
    throw error;
  }
}

/**
 * Get letter status from Lob
 */
export async function getLetterStatus(letterId: string): Promise<{
  id: string;
  status: string;
  tracking_number?: string;
  expected_delivery_date?: string;
  carrier?: string;
}> {
  if (!process.env.LOB_API_KEY) {
    throw new Error('LOB_API_KEY not configured');
  }

  const lobApiKey = process.env.LOB_API_KEY;
  const authHeader = 'Basic ' + Buffer.from(lobApiKey + ':').toString('base64');

  const response = await fetch(`https://api.lob.com/v1/letters/${letterId}`, {
    method: 'GET',
    headers: {
      'Authorization': authHeader
    }
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Lob API error: ${errorData.error?.message || 'Unknown error'}`);
  }

  const data = await response.json();

  return {
    id: data.id,
    status: data.send_date ? 'mailed' : 'processing',
    tracking_number: data.tracking_number,
    expected_delivery_date: data.expected_delivery_date,
    carrier: data.carrier
  };
}
