/**
 * PDF Contest Letter Generator
 * Generates professional PDF contest letters using PDFKit
 */

import PDFDocument from 'pdfkit';

export interface LetterData {
  ticketNumber: string;
  issueDate: string;
  violationCode: string;
  violationDescription: string;
  location: string;
  amount: number | string;
  userName: string;
  userAddress: string;
  userCity: string;
  userState: string;
  userZip: string;
  licensePlate: string;
  licenseState: string;
  letterBody: string;
  foiaStats?: {
    totalContests: number;
    winRate: number;
  };
}

export async function generateLetterPDF(data: LetterData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const today = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      // Date
      doc.fontSize(11).font('Helvetica').text(today, { align: 'left' });
      doc.moveDown(2);

      // Sender
      doc.text(data.userName || '[YOUR NAME]');
      doc.text(data.userAddress || '[YOUR ADDRESS]');
      doc.text(`${data.userCity || '[CITY]'}, ${data.userState || 'IL'} ${data.userZip || '[ZIP]'}`);
      doc.moveDown(2);

      // Recipient
      doc.text('City of Chicago');
      doc.text('Department of Administrative Hearings');
      doc.text('400 W. Superior Street');
      doc.text('Chicago, IL 60654');
      doc.moveDown(2);

      // Subject
      doc.font('Helvetica-Bold').text(`RE: Contest of Parking Ticket #${data.ticketNumber}`);
      doc.font('Helvetica');
      doc.moveDown(1);

      // Ticket info
      doc.text(`License Plate: ${data.licensePlate} (${data.licenseState || 'IL'})`);
      doc.text(`Violation: ${data.violationCode} - ${data.violationDescription}`);
      doc.text(`Issue Date: ${data.issueDate} | Location: ${data.location}`);
      doc.text(`Amount: $${typeof data.amount === 'number' ? data.amount.toFixed(2) : data.amount}`);
      doc.moveDown(2);

      // Salutation
      doc.text('To Whom It May Concern:');
      doc.moveDown(1);

      // Body - extract main content from AI letter
      const lines = data.letterBody.split('\n');
      let inBody = false;

      for (const line of lines) {
        const trimmed = line.trim();
        if (!inBody) {
          if (trimmed.includes('To Whom It May Concern') || trimmed.includes('Dear ')) {
            inBody = true;
            continue;
          }
          continue;
        }
        if (trimmed.includes('Sincerely') || trimmed.includes('Respectfully')) break;
        if (trimmed) {
          doc.fontSize(10).text(trimmed, { align: 'justify', lineGap: 1 });
          doc.moveDown(0.4);
        }
      }

      // Signature
      doc.moveDown(1);
      doc.fontSize(11).text('Sincerely,');
      doc.moveDown(2);
      doc.text(data.userName || '[YOUR NAME]');

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor('#888888');
      if (data.foiaStats) {
        doc.text(
          `${data.foiaStats.winRate}% win rate from ${data.foiaStats.totalContests.toLocaleString()} similar contests`,
          { align: 'center' }
        );
      }
      doc.text('Generated by Autopilot America - www.autopilotamerica.com', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export async function generateBatchLettersPDF(letters: LetterData[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      letters.forEach((data, index) => {
        if (index > 0) doc.addPage();

        const today = new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        });

        doc.fontSize(11).font('Helvetica').fillColor('#000000').text(today);
        doc.moveDown(1.5);

        doc.text(data.userName || '[YOUR NAME]');
        doc.text(data.userAddress || '[YOUR ADDRESS]');
        doc.text(`${data.userCity || '[CITY]'}, ${data.userState || 'IL'} ${data.userZip || '[ZIP]'}`);
        doc.moveDown(1.5);

        doc.text('City of Chicago');
        doc.text('Department of Administrative Hearings');
        doc.text('400 W. Superior Street');
        doc.text('Chicago, IL 60654');
        doc.moveDown(1.5);

        doc.font('Helvetica-Bold').text(`RE: Contest of Parking Ticket #${data.ticketNumber}`);
        doc.font('Helvetica').moveDown(0.8);

        doc.fontSize(10);
        doc.text(`License Plate: ${data.licensePlate} (${data.licenseState || 'IL'})`);
        doc.text(`Violation: ${data.violationCode} - ${data.violationDescription}`);
        doc.text(`Issue Date: ${data.issueDate} | Location: ${data.location} | Amount: $${typeof data.amount === 'number' ? data.amount.toFixed(2) : data.amount}`);
        doc.moveDown(1);
        doc.fontSize(11).text('To Whom It May Concern:');
        doc.moveDown(0.8);

        const lines = data.letterBody.split('\n');
        let inBody = false;

        for (const line of lines) {
          const trimmed = line.trim();
          if (!inBody) {
            if (trimmed.includes('To Whom It May Concern') || trimmed.includes('Dear ')) {
              inBody = true;
              continue;
            }
            continue;
          }
          if (trimmed.includes('Sincerely') || trimmed.includes('Respectfully')) break;
          if (trimmed) {
            doc.fontSize(10).text(trimmed, { align: 'justify', lineGap: 1 });
            doc.moveDown(0.4);
          }
        }

        doc.moveDown(1);
        doc.fontSize(11).text('Sincerely,');
        doc.moveDown(2);
        doc.text(data.userName || '[YOUR NAME]');

        doc.moveDown(1);
        doc.fontSize(8).fillColor('#888888');
        doc.text(`Ticket #${data.ticketNumber} | Page ${index + 1} of ${letters.length}`, { align: 'center' });
        if (data.foiaStats) {
          doc.text(`${data.foiaStats.winRate}% win rate from ${data.foiaStats.totalContests.toLocaleString()} similar contests`, { align: 'center' });
        }
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
