import { useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Footer from '../components/Footer';

interface ContestReason {
  reason: string;
  win_probability: number;
  evidence_needed: string;
  explanation: string;
}

interface ContestResult {
  violation_type: string;
  typical_fine: number;
  contest_difficulty: string;
  recommended_reason: ContestReason | null;
  all_reasons: ContestReason[];
  expected_savings: number;
  average_win_probability: string;
  recommendation: string;
}

const VIOLATION_TYPES = [
  'Street Cleaning',
  'Expired Meter',
  'Residential Permit Zone',
  'No City Sticker',
  'Fire Hydrant',
  'Expired Plate/Registration',
  'Snow Route Parking'
];

export default function TicketContest() {
  const [violationType, setViolationType] = useState('');
  const [situationDescription, setSituationDescription] = useState('');
  const [ticketNumber, setTicketNumber] = useState('');
  const [ticketDate, setTicketDate] = useState('');
  const [result, setResult] = useState<ContestResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showInstructions, setShowInstructions] = useState(false);
  const [uploadingPhoto, setUploadingPhoto] = useState(false);
  const [photoMode, setPhotoMode] = useState(false);
  const router = useRouter();

  const analyzeTicket = async () => {
    if (!violationType) {
      setError('Please select a violation type');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/contest-ticket', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          violation_description: violationType,
          situation_description: situationDescription || undefined
        })
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to analyze ticket');
      }

      setResult(data);
      setShowInstructions(true);
    } catch (err: any) {
      setError(err.message || 'Something went wrong');
    } finally {
      setLoading(false);
    }
  };

  const downloadContestLetter = () => {
    if (!result || !ticketNumber) {
      alert('Please enter your ticket number first');
      return;
    }

    const reason = result.recommended_reason || result.all_reasons[0];
    const letter = `TICKET CONTEST LETTER

Ticket Number: ${ticketNumber}
${ticketDate ? `Ticket Date: ${ticketDate}` : ''}
Violation: ${result.violation_type}

TO: City of Chicago Department of Administrative Hearings

RE: Contest of Parking Violation #${ticketNumber}

I am writing to contest the above-referenced parking ticket on the following grounds:

REASON FOR CONTEST:
${reason.reason}

EXPLANATION:
${reason.explanation}

EVIDENCE:
${reason.evidence_needed}

Based on the above, I respectfully request that this ticket be dismissed.

Sincerely,
[Your Name]
[Your Address]
[Your Phone Number]
[Date]

---
Generated by Autopilot America Ticket Contest Assistant
Win Probability: ${(reason.win_probability * 100).toFixed(0)}%
`;

    const blob = new Blob([letter], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ticket-contest-${ticketNumber}.txt`;
    a.click();
  };

  const handlePhotoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploadingPhoto(true);
    setError('');

    try {
      // Convert to base64
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = async () => {
        const base64 = reader.result as string;

        // Analyze photo
        const response = await fetch('/api/analyze-ticket-photo', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ imageBase64: base64 })
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.error || 'Failed to analyze photo');
        }

        // Auto-fill form
        if (data.violation_type && data.violation_type !== 'Other') {
          setViolationType(data.violation_type);
        }
        if (data.ticket_number) {
          setTicketNumber(data.ticket_number);
        }
        if (data.ticket_date) {
          setTicketDate(data.ticket_date);
        }
        if (data.violation_description) {
          setSituationDescription(data.violation_description);
        }

        setPhotoMode(false);
        alert('✅ Ticket analyzed! Review the auto-filled info below.');
      };
    } catch (err: any) {
      setError(err.message || 'Failed to analyze photo');
    } finally {
      setUploadingPhoto(false);
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return '#10b981';
      case 'medium': return '#f59e0b';
      case 'hard': return '#dc2626';
      default: return '#6b7280';
    }
  };

  return (
    <>
      <Head>
        <title>Ticket Contest Assistant | Autopilot America</title>
        <meta name="description" content="AI-powered ticket contest advisor - find out if your parking ticket is worth fighting" />
      </Head>

      <div style={{ minHeight: '100vh', backgroundColor: '#f9fafb', paddingBottom: '60px' }}>
        {/* Header */}
        <div style={{ backgroundColor: 'white', borderBottom: '1px solid #e5e7eb', padding: '20px' }}>
          <div style={{ maxWidth: '900px', margin: '0 auto' }}>
            <button
              onClick={() => router.push('/')}
              style={{
                background: 'none',
                border: 'none',
                color: '#0052cc',
                cursor: 'pointer',
                fontSize: '14px',
                marginBottom: '10px'
              }}
            >
              ← Back to Home
            </button>
            <h1 style={{ margin: '0', fontSize: '32px', fontWeight: 'bold', color: '#111827' }}>
              ⚖️ Ticket Contest Assistant
            </h1>
            <p style={{ margin: '10px 0 0 0', color: '#6b7280', fontSize: '16px' }}>
              AI-powered analysis to determine if your parking ticket is worth contesting
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div style={{ maxWidth: '900px', margin: '30px auto', padding: '0 20px' }}>
          {/* Input Form */}
          <div style={{
            backgroundColor: 'white',
            padding: '30px',
            borderRadius: '12px',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
            marginBottom: '30px'
          }}>
            <h2 style={{ margin: '0 0 8px 0', fontSize: '20px', fontWeight: '600', color: '#111827' }}>
              Contest Your Ticket in 3 Steps
            </h2>
            <p style={{ margin: '0 0 16px 0', fontSize: '14px', color: '#6b7280' }}>
              Free AI-powered analysis + downloadable contest letter
            </p>

            {/* Photo Upload Option */}
            <div style={{
              padding: '16px',
              backgroundColor: '#eff6ff',
              border: '2px dashed #3b82f6',
              borderRadius: '8px',
              textAlign: 'center',
              marginBottom: '24px'
            }}>
              <p style={{ margin: '0 0 12px 0', fontSize: '15px', fontWeight: '600', color: '#1e40af' }}>
                📸 Quick Option: Upload Ticket Photo
              </p>
              <p style={{ margin: '0 0 12px 0', fontSize: '13px', color: '#6b7280' }}>
                AI will auto-fill violation type, ticket number, and details
              </p>
              <label style={{
                display: 'inline-block',
                padding: '10px 24px',
                backgroundColor: '#3b82f6',
                color: 'white',
                borderRadius: '6px',
                cursor: uploadingPhoto ? 'not-allowed' : 'pointer',
                fontSize: '14px',
                fontWeight: '600'
              }}>
                {uploadingPhoto ? '🔄 Analyzing Photo...' : '📷 Upload Ticket Photo'}
                <input
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={handlePhotoUpload}
                  disabled={uploadingPhoto}
                  style={{ display: 'none' }}
                />
              </label>
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', fontWeight: '600', color: '#374151' }}>
                1. Select Violation Type <span style={{ color: '#dc2626' }}>*</span>
              </label>
              <select
                value={violationType}
                onChange={(e) => setViolationType(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '6px',
                  fontSize: '16px',
                  fontFamily: 'inherit',
                  backgroundColor: 'white',
                  cursor: 'pointer'
                }}
              >
                <option value="">-- Choose your violation --</option>
                {VIOLATION_TYPES.map(type => (
                  <option key={type} value={type}>{type}</option>
                ))}
              </select>
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', fontWeight: '600', color: '#374151' }}>
                2. Describe Your Situation (Optional but recommended)
              </label>
              <textarea
                placeholder="e.g., The street cleaning sign was covered by a tree branch, I couldn't see it from my car..."
                value={situationDescription}
                onChange={(e) => setSituationDescription(e.target.value)}
                rows={3}
                style={{
                  width: '100%',
                  padding: '12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '6px',
                  fontSize: '16px',
                  fontFamily: 'inherit',
                  resize: 'vertical'
                }}
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
              <div>
                <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', fontWeight: '600', color: '#374151' }}>
                  Ticket Number (Optional)
                </label>
                <input
                  type="text"
                  placeholder="e.g., 123456789"
                  value={ticketNumber}
                  onChange={(e) => setTicketNumber(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '12px',
                    border: '1px solid #d1d5db',
                    borderRadius: '6px',
                    fontSize: '16px',
                    fontFamily: 'inherit'
                  }}
                />
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', fontWeight: '600', color: '#374151' }}>
                  Ticket Date (Optional)
                </label>
                <input
                  type="date"
                  value={ticketDate}
                  onChange={(e) => setTicketDate(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '12px',
                    border: '1px solid #d1d5db',
                    borderRadius: '6px',
                    fontSize: '16px',
                    fontFamily: 'inherit'
                  }}
                />
              </div>
            </div>

            {error && (
              <div style={{
                padding: '12px',
                backgroundColor: '#fee2e2',
                border: '1px solid #fecaca',
                borderRadius: '6px',
                color: '#991b1b',
                fontSize: '14px',
                marginBottom: '20px'
              }}>
                {error}
              </div>
            )}

            <button
              onClick={analyzeTicket}
              disabled={loading}
              style={{
                width: '100%',
                padding: '14px',
                backgroundColor: loading ? '#9ca3af' : '#0052cc',
                color: 'white',
                border: 'none',
                borderRadius: '6px',
                fontSize: '16px',
                fontWeight: '600',
                cursor: loading ? 'not-allowed' : 'pointer'
              }}
            >
              {loading ? 'Analyzing...' : '3. Analyze & Get Contest Strategy'}
            </button>
          </div>

          {/* Results */}
          {result && (
            <>
              {/* Main Recommendation */}
              <div style={{
                backgroundColor: 'white',
                padding: '30px',
                borderRadius: '12px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
                marginBottom: '20px',
                border: `3px solid ${result.recommendation.includes('STRONGLY') ? '#10b981' : result.recommendation.includes('RECOMMEND') ? '#f59e0b' : '#6b7280'}`
              }}>
                <h2 style={{ margin: '0 0 16px 0', fontSize: '24px', fontWeight: 'bold', color: '#111827' }}>
                  {result.violation_type}
                </h2>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '20px', marginBottom: '20px' }}>
                  <div>
                    <p style={{ margin: '0 0 4px 0', fontSize: '12px', color: '#6b7280', fontWeight: '600' }}>TYPICAL FINE</p>
                    <p style={{ margin: '0', fontSize: '28px', fontWeight: 'bold', color: '#dc2626' }}>${result.typical_fine}</p>
                  </div>
                  <div>
                    <p style={{ margin: '0 0 4px 0', fontSize: '12px', color: '#6b7280', fontWeight: '600' }}>WIN PROBABILITY</p>
                    <p style={{ margin: '0', fontSize: '28px', fontWeight: 'bold', color: '#10b981' }}>{result.average_win_probability}</p>
                  </div>
                  <div>
                    <p style={{ margin: '0 0 4px 0', fontSize: '12px', color: '#6b7280', fontWeight: '600' }}>EXPECTED SAVINGS</p>
                    <p style={{ margin: '0', fontSize: '28px', fontWeight: 'bold', color: '#10b981' }}>${result.expected_savings}</p>
                  </div>
                </div>

                <div style={{
                  padding: '16px',
                  backgroundColor: result.recommendation.includes('STRONGLY') ? '#d1fae5' : result.recommendation.includes('RECOMMEND') ? '#fef3c7' : '#f3f4f6',
                  borderRadius: '8px',
                  marginBottom: '20px'
                }}>
                  <p style={{
                    margin: '0',
                    fontSize: '16px',
                    fontWeight: '600',
                    color: result.recommendation.includes('STRONGLY') ? '#065f46' : result.recommendation.includes('RECOMMEND') ? '#92400e' : '#374151'
                  }}>
                    {result.recommendation}
                  </p>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '14px', color: '#6b7280' }}>Contest Difficulty:</span>
                  <span style={{
                    padding: '4px 12px',
                    backgroundColor: `${getDifficultyColor(result.contest_difficulty)}15`,
                    color: getDifficultyColor(result.contest_difficulty),
                    borderRadius: '4px',
                    fontSize: '14px',
                    fontWeight: '600',
                    textTransform: 'uppercase'
                  }}>
                    {result.contest_difficulty}
                  </span>
                </div>
              </div>

              {/* Action Buttons */}
              <div style={{
                backgroundColor: 'white',
                padding: '24px',
                borderRadius: '12px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
                marginBottom: '20px'
              }}>
                <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', fontWeight: '600', color: '#111827' }}>
                  📝 Next Steps
                </h3>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '16px' }}>
                  <button
                    onClick={downloadContestLetter}
                    style={{
                      padding: '12px 16px',
                      backgroundColor: '#10b981',
                      color: 'white',
                      border: 'none',
                      borderRadius: '6px',
                      fontSize: '15px',
                      fontWeight: '600',
                      cursor: 'pointer'
                    }}
                  >
                    📄 Download Contest Letter
                  </button>
                  <button
                    onClick={() => setShowInstructions(!showInstructions)}
                    style={{
                      padding: '12px 16px',
                      backgroundColor: '#3b82f6',
                      color: 'white',
                      border: 'none',
                      borderRadius: '6px',
                      fontSize: '15px',
                      fontWeight: '600',
                      cursor: 'pointer'
                    }}
                  >
                    📋 {showInstructions ? 'Hide' : 'Show'} Filing Instructions
                  </button>
                </div>
                {showInstructions && (
                  <div style={{
                    padding: '16px',
                    backgroundColor: '#f9fafb',
                    borderRadius: '8px',
                    fontSize: '14px',
                    lineHeight: '1.6'
                  }}>
                    <p style={{ margin: '0 0 12px 0', fontWeight: '600', color: '#111827' }}>
                      How to Contest Your Ticket (Chicago):
                    </p>
                    <ol style={{ margin: '0', paddingLeft: '20px', color: '#374151' }}>
                      <li style={{ marginBottom: '8px' }}>
                        <strong>Download</strong> your contest letter above (edit with your name/address)
                      </li>
                      <li style={{ marginBottom: '8px' }}>
                        <strong>Gather evidence:</strong> {result.recommended_reason?.evidence_needed || result.all_reasons[0].evidence_needed}
                      </li>
                      <li style={{ marginBottom: '8px' }}>
                        <strong>Submit online:</strong> Visit{' '}
                        <a href="https://www.cityofchicago.org/city/en/depts/fin/provdrs/parking_and_redlightcitationadministration/svcs/contest_a_citation.html" target="_blank" rel="noopener noreferrer" style={{ color: '#0052cc' }}>
                          chicago.gov/contestticket
                        </a>
                      </li>
                      <li style={{ marginBottom: '8px' }}>
                        <strong>OR mail to:</strong><br />
                        City of Chicago Department of Finance<br />
                        PO Box 88298<br />
                        Chicago, IL 60680-1298
                      </li>
                      <li style={{ marginBottom: '8px' }}>
                        <strong>Deadline:</strong> Contest within 21 days of ticket date
                      </li>
                      <li style={{ marginBottom: '0' }}>
                        <strong>Hearing:</strong> If contested, you may need to attend a hearing. Bring all evidence!
                      </li>
                    </ol>
                    <div style={{
                      marginTop: '16px',
                      padding: '12px',
                      backgroundColor: '#fef3c7',
                      borderRadius: '6px',
                      fontSize: '13px',
                      color: '#92400e'
                    }}>
                      <strong>💡 Pro Tip:</strong> Take photos/videos of evidence immediately. Signs disappear, conditions change!
                    </div>
                  </div>
                )}
              </div>

              {/* Recommended Reason (if situation provided) */}
              {result.recommended_reason && (
                <div style={{
                  backgroundColor: 'white',
                  padding: '24px',
                  borderRadius: '12px',
                  boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
                  marginBottom: '20px',
                  border: '2px solid #3b82f6'
                }}>
                  <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', fontWeight: '600', color: '#111827' }}>
                    🎯 Best Match for Your Situation
                  </h3>
                  <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: '12px'
                  }}>
                    <p style={{ margin: '0', fontSize: '16px', fontWeight: '600', color: '#111827' }}>
                      {result.recommended_reason.reason}
                    </p>
                    <span style={{
                      padding: '4px 12px',
                      backgroundColor: '#10b98115',
                      color: '#10b981',
                      borderRadius: '4px',
                      fontSize: '14px',
                      fontWeight: '600'
                    }}>
                      {(result.recommended_reason.win_probability * 100).toFixed(0)}% Win Rate
                    </span>
                  </div>
                  <p style={{ margin: '0 0 12px 0', fontSize: '14px', color: '#6b7280' }}>
                    {result.recommended_reason.explanation}
                  </p>
                  <div style={{ padding: '12px', backgroundColor: '#f3f4f6', borderRadius: '6px' }}>
                    <p style={{ margin: '0 0 4px 0', fontSize: '12px', fontWeight: '600', color: '#374151' }}>Evidence Needed:</p>
                    <p style={{ margin: '0', fontSize: '14px', color: '#6b7280' }}>{result.recommended_reason.evidence_needed}</p>
                  </div>
                </div>
              )}

              {/* All Contest Reasons */}
              <div style={{
                backgroundColor: 'white',
                padding: '24px',
                borderRadius: '12px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
              }}>
                <h3 style={{ margin: '0 0 20px 0', fontSize: '18px', fontWeight: '600', color: '#111827' }}>
                  All Contestable Reasons
                </h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  {result.all_reasons.map((reason, index) => (
                    <div
                      key={index}
                      style={{
                        padding: '16px',
                        border: '1px solid #e5e7eb',
                        borderRadius: '8px'
                      }}
                    >
                      <div style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        marginBottom: '8px'
                      }}>
                        <p style={{ margin: '0', fontSize: '15px', fontWeight: '600', color: '#111827' }}>
                          {reason.reason}
                        </p>
                        <span style={{
                          padding: '3px 10px',
                          backgroundColor: reason.win_probability > 0.8 ? '#10b98115' : reason.win_probability > 0.6 ? '#f59e0b15' : '#6b728015',
                          color: reason.win_probability > 0.8 ? '#10b981' : reason.win_probability > 0.6 ? '#f59e0b' : '#6b7280',
                          borderRadius: '4px',
                          fontSize: '13px',
                          fontWeight: '600'
                        }}>
                          {(reason.win_probability * 100).toFixed(0)}%
                        </span>
                      </div>
                      <p style={{ margin: '0 0 8px 0', fontSize: '13px', color: '#6b7280' }}>
                        {reason.explanation}
                      </p>
                      <p style={{ margin: '0', fontSize: '12px', color: '#9ca3af' }}>
                        <strong>Evidence needed:</strong> {reason.evidence_needed}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}
        </div>
      </div>

      <Footer />
    </>
  );
}
